//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  project: Project;
  projectConnection: ProjectConnection;
  blog: Blog;
  blogConnection: BlogConnection;
  profile: Profile;
  profileConnection: ProfileConnection;
  skills: Skills;
  skillsConnection: SkillsConnection;
  artworks: Artworks;
  artworksConnection: ArtworksConnection;
  techStack: TechStack;
  techStackConnection: TechStackConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryProfileArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProfileConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfileFilter>;
};


export type QuerySkillsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySkillsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
};


export type QueryArtworksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtworksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
};


export type QueryTechStackArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTechStackConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechStackFilter>;
};

export type DocumentFilter = {
  project?: InputMaybe<ProjectFilter>;
  blog?: InputMaybe<BlogFilter>;
  profile?: InputMaybe<ProfileFilter>;
  skills?: InputMaybe<SkillsFilter>;
  artworks?: InputMaybe<ArtworksFilter>;
  techStack?: InputMaybe<TechStackFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Project | Blog | Profile | Skills | Artworks | TechStack | Folder;

export type ProjectItemsStats = {
  __typename?: 'ProjectItemsStats';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type ProjectItems = {
  __typename?: 'ProjectItems';
  id: Scalars['String']['output'];
  title: Scalars['String']['output'];
  tagline: Scalars['String']['output'];
  description: Scalars['String']['output'];
  tech?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  impact?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  accentColor?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  github?: Maybe<Scalars['String']['output']>;
  screenshot?: Maybe<Scalars['String']['output']>;
  rarity?: Maybe<Scalars['String']['output']>;
  rpgDescription?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<ProjectItemsStats>>>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  items?: Maybe<Array<Maybe<ProjectItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProjectItemsStatsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type ProjectItemsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tech?: InputMaybe<StringFilter>;
  impact?: InputMaybe<StringFilter>;
  accentColor?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
  screenshot?: InputMaybe<ImageFilter>;
  rarity?: InputMaybe<StringFilter>;
  rpgDescription?: InputMaybe<StringFilter>;
  stats?: InputMaybe<ProjectItemsStatsFilter>;
};

export type ProjectFilter = {
  items?: InputMaybe<ProjectItemsFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type BlogItems = {
  __typename?: 'BlogItems';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  readTime?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
  content?: Maybe<Scalars['String']['output']>;
};

export type Blog = Node & Document & {
  __typename?: 'Blog';
  items?: Maybe<Array<Maybe<BlogItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogItemsFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  content?: InputMaybe<StringFilter>;
};

export type BlogFilter = {
  items?: InputMaybe<BlogItemsFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type ProfileSocials = {
  __typename?: 'ProfileSocials';
  platform: Scalars['String']['output'];
  url: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type ProfileNavItems = {
  __typename?: 'ProfileNavItems';
  id: Scalars['String']['output'];
  label: Scalars['String']['output'];
  expandable?: Maybe<Scalars['Boolean']['output']>;
  download?: Maybe<Scalars['Boolean']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type ProfileStoryChapters = {
  __typename?: 'ProfileStoryChapters';
  title?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
};

export type ProfileStory = {
  __typename?: 'ProfileStory';
  title?: Maybe<Scalars['String']['output']>;
  chapters?: Maybe<Array<Maybe<ProfileStoryChapters>>>;
  highlight?: Maybe<Scalars['String']['output']>;
  skills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Profile = Node & Document & {
  __typename?: 'Profile';
  name: Scalars['String']['output'];
  firstName?: Maybe<Scalars['String']['output']>;
  lastName?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  resume?: Maybe<Scalars['String']['output']>;
  socials?: Maybe<Array<Maybe<ProfileSocials>>>;
  navItems?: Maybe<Array<Maybe<ProfileNavItems>>>;
  story?: Maybe<ProfileStory>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProfileSocialsFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type ProfileNavItemsFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  expandable?: InputMaybe<BooleanFilter>;
  download?: InputMaybe<BooleanFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ProfileStoryChaptersFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type ProfileStoryFilter = {
  title?: InputMaybe<StringFilter>;
  chapters?: InputMaybe<ProfileStoryChaptersFilter>;
  highlight?: InputMaybe<StringFilter>;
  skills?: InputMaybe<StringFilter>;
};

export type ProfileFilter = {
  name?: InputMaybe<StringFilter>;
  firstName?: InputMaybe<StringFilter>;
  lastName?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
  resume?: InputMaybe<StringFilter>;
  socials?: InputMaybe<ProfileSocialsFilter>;
  navItems?: InputMaybe<ProfileNavItemsFilter>;
  story?: InputMaybe<ProfileStoryFilter>;
};

export type ProfileConnectionEdges = {
  __typename?: 'ProfileConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Profile>;
};

export type ProfileConnection = Connection & {
  __typename?: 'ProfileConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProfileConnectionEdges>>>;
};

export type SkillsRpgSkills = {
  __typename?: 'SkillsRpgSkills';
  name?: Maybe<Scalars['String']['output']>;
  level?: Maybe<Scalars['Float']['output']>;
  maxLevel?: Maybe<Scalars['Float']['output']>;
  xp?: Maybe<Scalars['Float']['output']>;
  maxXp?: Maybe<Scalars['Float']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SkillsSoftSkills = {
  __typename?: 'SkillsSoftSkills';
  name?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  level?: Maybe<Scalars['Float']['output']>;
  color?: Maybe<Scalars['String']['output']>;
};

export type Skills = Node & Document & {
  __typename?: 'Skills';
  rpgSkills?: Maybe<Array<Maybe<SkillsRpgSkills>>>;
  softSkills?: Maybe<Array<Maybe<SkillsSoftSkills>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SkillsRpgSkillsFilter = {
  name?: InputMaybe<StringFilter>;
  level?: InputMaybe<NumberFilter>;
  maxLevel?: InputMaybe<NumberFilter>;
  xp?: InputMaybe<NumberFilter>;
  maxXp?: InputMaybe<NumberFilter>;
  icon?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SkillsSoftSkillsFilter = {
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  level?: InputMaybe<NumberFilter>;
  color?: InputMaybe<StringFilter>;
};

export type SkillsFilter = {
  rpgSkills?: InputMaybe<SkillsRpgSkillsFilter>;
  softSkills?: InputMaybe<SkillsSoftSkillsFilter>;
};

export type SkillsConnectionEdges = {
  __typename?: 'SkillsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Skills>;
};

export type SkillsConnection = Connection & {
  __typename?: 'SkillsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SkillsConnectionEdges>>>;
};

export type ArtworksItems = {
  __typename?: 'ArtworksItems';
  id: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  likes?: Maybe<Scalars['Float']['output']>;
  views?: Maybe<Scalars['String']['output']>;
};

export type Artworks = Node & Document & {
  __typename?: 'Artworks';
  items?: Maybe<Array<Maybe<ArtworksItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ArtworksItemsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  year?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  likes?: InputMaybe<NumberFilter>;
  views?: InputMaybe<StringFilter>;
};

export type ArtworksFilter = {
  items?: InputMaybe<ArtworksItemsFilter>;
};

export type ArtworksConnectionEdges = {
  __typename?: 'ArtworksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Artworks>;
};

export type ArtworksConnection = Connection & {
  __typename?: 'ArtworksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArtworksConnectionEdges>>>;
};

export type TechStackTechIcons = {
  __typename?: 'TechStackTechIcons';
  name?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  size?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type TechStackHeroTechStack = {
  __typename?: 'TechStackHeroTechStack';
  name?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type TechStack = Node & Document & {
  __typename?: 'TechStack';
  techIcons?: Maybe<Array<Maybe<TechStackTechIcons>>>;
  heroTechStack?: Maybe<Array<Maybe<TechStackHeroTechStack>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TechStackTechIconsFilter = {
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  size?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type TechStackHeroTechStackFilter = {
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type TechStackFilter = {
  techIcons?: InputMaybe<TechStackTechIconsFilter>;
  heroTechStack?: InputMaybe<TechStackHeroTechStackFilter>;
};

export type TechStackConnectionEdges = {
  __typename?: 'TechStackConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TechStack>;
};

export type TechStackConnection = Connection & {
  __typename?: 'TechStackConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TechStackConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProject: Project;
  createProject: Project;
  updateBlog: Blog;
  createBlog: Blog;
  updateProfile: Profile;
  createProfile: Profile;
  updateSkills: Skills;
  createSkills: Skills;
  updateArtworks: Artworks;
  createArtworks: Artworks;
  updateTechStack: TechStack;
  createTechStack: TechStack;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateProfileArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfileMutation;
};


export type MutationCreateProfileArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfileMutation;
};


export type MutationUpdateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationCreateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationUpdateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationCreateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationUpdateTechStackArgs = {
  relativePath: Scalars['String']['input'];
  params: TechStackMutation;
};


export type MutationCreateTechStackArgs = {
  relativePath: Scalars['String']['input'];
  params: TechStackMutation;
};

export type DocumentUpdateMutation = {
  project?: InputMaybe<ProjectMutation>;
  blog?: InputMaybe<BlogMutation>;
  profile?: InputMaybe<ProfileMutation>;
  skills?: InputMaybe<SkillsMutation>;
  artworks?: InputMaybe<ArtworksMutation>;
  techStack?: InputMaybe<TechStackMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  project?: InputMaybe<ProjectMutation>;
  blog?: InputMaybe<BlogMutation>;
  profile?: InputMaybe<ProfileMutation>;
  skills?: InputMaybe<SkillsMutation>;
  artworks?: InputMaybe<ArtworksMutation>;
  techStack?: InputMaybe<TechStackMutation>;
};

export type ProjectItemsStatsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tech?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  impact?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  accentColor?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  github?: InputMaybe<Scalars['String']['input']>;
  screenshot?: InputMaybe<Scalars['String']['input']>;
  rarity?: InputMaybe<Scalars['String']['input']>;
  rpgDescription?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<ProjectItemsStatsMutation>>>;
};

export type ProjectMutation = {
  items?: InputMaybe<Array<InputMaybe<ProjectItemsMutation>>>;
};

export type BlogItemsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type BlogMutation = {
  items?: InputMaybe<Array<InputMaybe<BlogItemsMutation>>>;
};

export type ProfileSocialsMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type ProfileNavItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  expandable?: InputMaybe<Scalars['Boolean']['input']>;
  download?: InputMaybe<Scalars['Boolean']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type ProfileStoryChaptersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type ProfileStoryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  chapters?: InputMaybe<Array<InputMaybe<ProfileStoryChaptersMutation>>>;
  highlight?: InputMaybe<Scalars['String']['input']>;
  skills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProfileMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  firstName?: InputMaybe<Scalars['String']['input']>;
  lastName?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  resume?: InputMaybe<Scalars['String']['input']>;
  socials?: InputMaybe<Array<InputMaybe<ProfileSocialsMutation>>>;
  navItems?: InputMaybe<Array<InputMaybe<ProfileNavItemsMutation>>>;
  story?: InputMaybe<ProfileStoryMutation>;
};

export type SkillsRpgSkillsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['Float']['input']>;
  maxLevel?: InputMaybe<Scalars['Float']['input']>;
  xp?: InputMaybe<Scalars['Float']['input']>;
  maxXp?: InputMaybe<Scalars['Float']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SkillsSoftSkillsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['Float']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type SkillsMutation = {
  rpgSkills?: InputMaybe<Array<InputMaybe<SkillsRpgSkillsMutation>>>;
  softSkills?: InputMaybe<Array<InputMaybe<SkillsSoftSkillsMutation>>>;
};

export type ArtworksItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  likes?: InputMaybe<Scalars['Float']['input']>;
  views?: InputMaybe<Scalars['String']['input']>;
};

export type ArtworksMutation = {
  items?: InputMaybe<Array<InputMaybe<ArtworksItemsMutation>>>;
};

export type TechStackTechIconsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  size?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type TechStackHeroTechStackMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type TechStackMutation = {
  techIcons?: InputMaybe<Array<InputMaybe<TechStackTechIconsMutation>>>;
  heroTechStack?: InputMaybe<Array<InputMaybe<TechStackHeroTechStackMutation>>>;
};

export type ProjectPartsFragment = { __typename: 'Project', items?: Array<{ __typename: 'ProjectItems', id: string, title: string, tagline: string, description: string, tech?: Array<string | null> | null, impact?: Array<string | null> | null, accentColor?: string | null, year?: string | null, type?: string | null, url?: string | null, github?: string | null, screenshot?: string | null, rarity?: string | null, rpgDescription?: string | null, stats?: Array<{ __typename: 'ProjectItemsStats', label?: string | null, value?: string | null } | null> | null } | null> | null };

export type BlogPartsFragment = { __typename: 'Blog', items?: Array<{ __typename: 'BlogItems', slug: string, title: string, excerpt?: string | null, date?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, readTime?: string | null, author?: string | null, published?: boolean | null, content?: string | null } | null> | null };

export type ProfilePartsFragment = { __typename: 'Profile', name: string, firstName?: string | null, lastName?: string | null, title?: string | null, tagline?: string | null, bio?: string | null, email?: string | null, location?: string | null, avatar?: string | null, resume?: string | null, socials?: Array<{ __typename: 'ProfileSocials', platform: string, url: string, icon?: string | null, label?: string | null } | null> | null, navItems?: Array<{ __typename: 'ProfileNavItems', id: string, label: string, expandable?: boolean | null, download?: boolean | null, href?: string | null } | null> | null, story?: { __typename: 'ProfileStory', title?: string | null, highlight?: string | null, skills?: Array<string | null> | null, chapters?: Array<{ __typename: 'ProfileStoryChapters', title?: string | null, content?: string | null } | null> | null } | null };

export type SkillsPartsFragment = { __typename: 'Skills', rpgSkills?: Array<{ __typename: 'SkillsRpgSkills', name?: string | null, level?: number | null, maxLevel?: number | null, xp?: number | null, maxXp?: number | null, icon?: string | null, category?: string | null, description?: string | null } | null> | null, softSkills?: Array<{ __typename: 'SkillsSoftSkills', name?: string | null, icon?: string | null, level?: number | null, color?: string | null } | null> | null };

export type ArtworksPartsFragment = { __typename: 'Artworks', items?: Array<{ __typename: 'ArtworksItems', id: string, title: string, description?: string | null, image?: string | null, year?: string | null, category?: string | null, likes?: number | null, views?: string | null } | null> | null };

export type TechStackPartsFragment = { __typename: 'TechStack', techIcons?: Array<{ __typename: 'TechStackTechIcons', name?: string | null, icon?: string | null, size?: string | null, category?: string | null } | null> | null, heroTechStack?: Array<{ __typename: 'TechStackHeroTechStack', name?: string | null, icon?: string | null } | null> | null };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProjectItems', id: string, title: string, tagline: string, description: string, tech?: Array<string | null> | null, impact?: Array<string | null> | null, accentColor?: string | null, year?: string | null, type?: string | null, url?: string | null, github?: string | null, screenshot?: string | null, rarity?: string | null, rpgDescription?: string | null, stats?: Array<{ __typename: 'ProjectItemsStats', label?: string | null, value?: string | null } | null> | null } | null> | null } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProjectItems', id: string, title: string, tagline: string, description: string, tech?: Array<string | null> | null, impact?: Array<string | null> | null, accentColor?: string | null, year?: string | null, type?: string | null, url?: string | null, github?: string | null, screenshot?: string | null, rarity?: string | null, rpgDescription?: string | null, stats?: Array<{ __typename: 'ProjectItemsStats', label?: string | null, value?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'BlogItems', slug: string, title: string, excerpt?: string | null, date?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, readTime?: string | null, author?: string | null, published?: boolean | null, content?: string | null } | null> | null } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'BlogItems', slug: string, title: string, excerpt?: string | null, date?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, readTime?: string | null, author?: string | null, published?: boolean | null, content?: string | null } | null> | null } | null } | null> | null } };

export type ProfileQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProfileQuery = { __typename?: 'Query', profile: { __typename: 'Profile', id: string, name: string, firstName?: string | null, lastName?: string | null, title?: string | null, tagline?: string | null, bio?: string | null, email?: string | null, location?: string | null, avatar?: string | null, resume?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'ProfileSocials', platform: string, url: string, icon?: string | null, label?: string | null } | null> | null, navItems?: Array<{ __typename: 'ProfileNavItems', id: string, label: string, expandable?: boolean | null, download?: boolean | null, href?: string | null } | null> | null, story?: { __typename: 'ProfileStory', title?: string | null, highlight?: string | null, skills?: Array<string | null> | null, chapters?: Array<{ __typename: 'ProfileStoryChapters', title?: string | null, content?: string | null } | null> | null } | null } };

export type ProfileConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfileFilter>;
}>;


export type ProfileConnectionQuery = { __typename?: 'Query', profileConnection: { __typename?: 'ProfileConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProfileConnectionEdges', cursor: string, node?: { __typename: 'Profile', id: string, name: string, firstName?: string | null, lastName?: string | null, title?: string | null, tagline?: string | null, bio?: string | null, email?: string | null, location?: string | null, avatar?: string | null, resume?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'ProfileSocials', platform: string, url: string, icon?: string | null, label?: string | null } | null> | null, navItems?: Array<{ __typename: 'ProfileNavItems', id: string, label: string, expandable?: boolean | null, download?: boolean | null, href?: string | null } | null> | null, story?: { __typename: 'ProfileStory', title?: string | null, highlight?: string | null, skills?: Array<string | null> | null, chapters?: Array<{ __typename: 'ProfileStoryChapters', title?: string | null, content?: string | null } | null> | null } | null } | null } | null> | null } };

export type SkillsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SkillsQuery = { __typename?: 'Query', skills: { __typename: 'Skills', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rpgSkills?: Array<{ __typename: 'SkillsRpgSkills', name?: string | null, level?: number | null, maxLevel?: number | null, xp?: number | null, maxXp?: number | null, icon?: string | null, category?: string | null, description?: string | null } | null> | null, softSkills?: Array<{ __typename: 'SkillsSoftSkills', name?: string | null, icon?: string | null, level?: number | null, color?: string | null } | null> | null } };

export type SkillsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
}>;


export type SkillsConnectionQuery = { __typename?: 'Query', skillsConnection: { __typename?: 'SkillsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SkillsConnectionEdges', cursor: string, node?: { __typename: 'Skills', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rpgSkills?: Array<{ __typename: 'SkillsRpgSkills', name?: string | null, level?: number | null, maxLevel?: number | null, xp?: number | null, maxXp?: number | null, icon?: string | null, category?: string | null, description?: string | null } | null> | null, softSkills?: Array<{ __typename: 'SkillsSoftSkills', name?: string | null, icon?: string | null, level?: number | null, color?: string | null } | null> | null } | null } | null> | null } };

export type ArtworksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArtworksQuery = { __typename?: 'Query', artworks: { __typename: 'Artworks', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ArtworksItems', id: string, title: string, description?: string | null, image?: string | null, year?: string | null, category?: string | null, likes?: number | null, views?: string | null } | null> | null } };

export type ArtworksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
}>;


export type ArtworksConnectionQuery = { __typename?: 'Query', artworksConnection: { __typename?: 'ArtworksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArtworksConnectionEdges', cursor: string, node?: { __typename: 'Artworks', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ArtworksItems', id: string, title: string, description?: string | null, image?: string | null, year?: string | null, category?: string | null, likes?: number | null, views?: string | null } | null> | null } | null } | null> | null } };

export type TechStackQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TechStackQuery = { __typename?: 'Query', techStack: { __typename: 'TechStack', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, techIcons?: Array<{ __typename: 'TechStackTechIcons', name?: string | null, icon?: string | null, size?: string | null, category?: string | null } | null> | null, heroTechStack?: Array<{ __typename: 'TechStackHeroTechStack', name?: string | null, icon?: string | null } | null> | null } };

export type TechStackConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechStackFilter>;
}>;


export type TechStackConnectionQuery = { __typename?: 'Query', techStackConnection: { __typename?: 'TechStackConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TechStackConnectionEdges', cursor: string, node?: { __typename: 'TechStack', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, techIcons?: Array<{ __typename: 'TechStackTechIcons', name?: string | null, icon?: string | null, size?: string | null, category?: string | null } | null> | null, heroTechStack?: Array<{ __typename: 'TechStackHeroTechStack', name?: string | null, icon?: string | null } | null> | null } | null } | null> | null } };

export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  items {
    __typename
    id
    title
    tagline
    description
    tech
    impact
    accentColor
    year
    type
    url
    github
    screenshot
    rarity
    rpgDescription
    stats {
      __typename
      label
      value
    }
  }
}
    `;
export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  items {
    __typename
    slug
    title
    excerpt
    date
    coverImage
    tags
    readTime
    author
    published
    content
  }
}
    `;
export const ProfilePartsFragmentDoc = gql`
    fragment ProfileParts on Profile {
  __typename
  name
  firstName
  lastName
  title
  tagline
  bio
  email
  location
  avatar
  resume
  socials {
    __typename
    platform
    url
    icon
    label
  }
  navItems {
    __typename
    id
    label
    expandable
    download
    href
  }
  story {
    __typename
    title
    chapters {
      __typename
      title
      content
    }
    highlight
    skills
  }
}
    `;
export const SkillsPartsFragmentDoc = gql`
    fragment SkillsParts on Skills {
  __typename
  rpgSkills {
    __typename
    name
    level
    maxLevel
    xp
    maxXp
    icon
    category
    description
  }
  softSkills {
    __typename
    name
    icon
    level
    color
  }
}
    `;
export const ArtworksPartsFragmentDoc = gql`
    fragment ArtworksParts on Artworks {
  __typename
  items {
    __typename
    id
    title
    description
    image
    year
    category
    likes
    views
  }
}
    `;
export const TechStackPartsFragmentDoc = gql`
    fragment TechStackParts on TechStack {
  __typename
  techIcons {
    __typename
    name
    icon
    size
    category
  }
  heroTechStack {
    __typename
    name
    icon
  }
}
    `;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const ProfileDocument = gql`
    query profile($relativePath: String!) {
  profile(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProfileParts
  }
}
    ${ProfilePartsFragmentDoc}`;
export const ProfileConnectionDocument = gql`
    query profileConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProfileFilter) {
  profileConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProfileParts
      }
    }
  }
}
    ${ProfilePartsFragmentDoc}`;
export const SkillsDocument = gql`
    query skills($relativePath: String!) {
  skills(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SkillsParts
  }
}
    ${SkillsPartsFragmentDoc}`;
export const SkillsConnectionDocument = gql`
    query skillsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SkillsFilter) {
  skillsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SkillsParts
      }
    }
  }
}
    ${SkillsPartsFragmentDoc}`;
export const ArtworksDocument = gql`
    query artworks($relativePath: String!) {
  artworks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtworksParts
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const ArtworksConnectionDocument = gql`
    query artworksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArtworksFilter) {
  artworksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtworksParts
      }
    }
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const TechStackDocument = gql`
    query techStack($relativePath: String!) {
  techStack(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TechStackParts
  }
}
    ${TechStackPartsFragmentDoc}`;
export const TechStackConnectionDocument = gql`
    query techStackConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TechStackFilter) {
  techStackConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TechStackParts
      }
    }
  }
}
    ${TechStackPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    profile(variables: ProfileQueryVariables, options?: C): Promise<{data: ProfileQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileQueryVariables, query: string}> {
        return requester<{data: ProfileQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileQueryVariables, query: string}, ProfileQueryVariables>(ProfileDocument, variables, options);
      },
    profileConnection(variables?: ProfileConnectionQueryVariables, options?: C): Promise<{data: ProfileConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileConnectionQueryVariables, query: string}> {
        return requester<{data: ProfileConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileConnectionQueryVariables, query: string}, ProfileConnectionQueryVariables>(ProfileConnectionDocument, variables, options);
      },
    skills(variables: SkillsQueryVariables, options?: C): Promise<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}> {
        return requester<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}, SkillsQueryVariables>(SkillsDocument, variables, options);
      },
    skillsConnection(variables?: SkillsConnectionQueryVariables, options?: C): Promise<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}> {
        return requester<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}, SkillsConnectionQueryVariables>(SkillsConnectionDocument, variables, options);
      },
    artworks(variables: ArtworksQueryVariables, options?: C): Promise<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}> {
        return requester<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}, ArtworksQueryVariables>(ArtworksDocument, variables, options);
      },
    artworksConnection(variables?: ArtworksConnectionQueryVariables, options?: C): Promise<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}> {
        return requester<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}, ArtworksConnectionQueryVariables>(ArtworksConnectionDocument, variables, options);
      },
    techStack(variables: TechStackQueryVariables, options?: C): Promise<{data: TechStackQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechStackQueryVariables, query: string}> {
        return requester<{data: TechStackQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechStackQueryVariables, query: string}, TechStackQueryVariables>(TechStackDocument, variables, options);
      },
    techStackConnection(variables?: TechStackConnectionQueryVariables, options?: C): Promise<{data: TechStackConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechStackConnectionQueryVariables, query: string}> {
        return requester<{data: TechStackConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechStackConnectionQueryVariables, query: string}, TechStackConnectionQueryVariables>(TechStackConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  